objects/POC_Customer__c.object
<CustomObject>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile_Number__c</fullName>
        <label>Mobile Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Reviewed__c</fullName>
        <label>Reviewed</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>POC - Customer</label>
    <nameField>
        <label>Customer ID</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/POCCustomerServiceTest.cls
@isTest
public without sharing class POCCustomerServiceTest {
    @isTest
    public static void POCCustomerServiceTest() {
        POC_Customer__c POCCustomer = new POC_Customer__c();
        POCCustomer.First_Name__c = 'Test';
        POCCustomer.Last_Name__c = 'Test';
        POCCustomer.Mobile_Number__c = '12345678901';
        POCCustomer.Country_Code__c = 'KR';
        POCCustomer.First_Name__c = 'Test';
        POCCustomer.First_Name__c = 'Test';
        POCCustomer.Reviewed__c = 'Yes';
        insert POCCustomer;
    }
}